### ISSUE TITLE
Parsing  json to yaml

### ISSUE THREAD

**Issue by sunnn** [circe/circe-yaml#298]
Hi im trying to parse a json string to yaml
current output
```
environment: kubernetes
actions:
  action1:
    read:
    - parquet:
      - path: hdfs
      - tableName: table
    transform:
    - transform:
      - columnToTransform: ''
      - coalesce: ''
    write:
    - parquet:
      - path: ''
```
but i require output in the below format as i couldnt and methods available for it
i need double quotes("") for environment,path,tab value in the yaml output
```
environment: "kubernetes"
actions:
  action1:
    read:
    - parquet:
      - path: "hdfs"
      - tab: "table"
    transform:
    - transform:
      - column: ''
      - partition: ''
    write:
    - parquet:
      - pth: 'hdfs'
```
