### ISSUE TITLE
Float / Double serialized in unnatural way

### ISSUE THREAD

**Issue by OndrejSpanel** [circe/circe-yaml#68]
Fractional double values are printed in a quite unexpected way. This is what I get:

```
            points:
            - x: -0
              y: 1
            - x: -5519150495529175e-16
              y: 1
            - x: -1
              y: 5519150495529175e-16
            - x: -1
              y: 0
```

While not incorrect, this is quite unexpected and not much human readable. This is what I would like to get:

```
            points:
            - x: -0
              y: 1
            - x: -0.5519150495529175
              y: 1
            - x: -1
              y: 0.55519150495529175
            - x: -1
              y: 0
```
